import "@/app/globals.css"
import { Inter } from "next/font/google";
import AppProviders from "@/providers/AppProviders";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn(inter.className, "antialiased")}>
				<AppProviders>
					<main className="min-h-screen">{children}</main>
				</AppProviders>
			</body>
		</html>
	);
}
